os: linux
dist: bionic
language: shell
services: docker
branches:
  only:
  - master
if: branch = master AND commit_message !~ /(no-deploy|wip)/
before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker info | grep Username
script:
    - ./build-and-push.sh terascope
