name: build
run-name: ${{ github.actor }} has triggered a build of the Terascope Base Image

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/node-base
      
jobs:
  compute-versions-from-env:
    runs-on: ubuntu-latest
    outputs:
      TERAFOUNDATION_KAFKA_CONNECTOR_VERSION: ${{ steps.dotenv.outputs.TERAFOUNDATION_KAFKA_CONNECTOR_VERSION }}
      IMAGE_VERSION: ${{ steps.dotenv.outputs.IMAGE_VERSION }}
      NODE_VERSIONS_ARRAY: ${{ steps.dotenv.outputs.NODE_VERSIONS_ARRAY }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Get versions from .env file using Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1.1.4
        with:
          log-variables: true
          keys-case: bypass

  build_matrix:
    needs: 'compute-versions-from-env'
    strategy:
      matrix:
        # NOTE: The NODE_VERSION_ARRAY is stored in the .env file.
        # In the case where a new node version introduces a breaking change,
        # replace the major version of the matrix to a pinned version.
        # Ex: ["18", "20", "22"] ---> ["18.19.1", "20", "22"]
        version: ${{ fromJSON(needs.compute-versions-from-env.outputs.NODE_VERSIONS_ARRAY) }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64,linux/amd64
      -
        name: Get timestamp for docker build
        id: docker_time_stamp
        run: echo "BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")" >> $GITHUB_ENV
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          build-args: |
            "NODE_VERSION=${{ matrix.version }}"
            "GITHUB_SHA=${{ github.sha }}"
            "BUILD_TIMESTAMP=${{ env.BUILD_TIMESTAMP }}"
            "TERAFOUNDATION_KAFKA_CONNECTOR_VERSION=${{ needs.compute-versions-from-env.outputs.TERAFOUNDATION_KAFKA_CONNECTOR_VERSION }}"
            "IMAGE_VERSION=${{ needs.compute-versions-from-env.outputs.IMAGE_VERSION }}"
          provenance: false
          sbom: true
          pull: true
          push: true
          file: ./Dockerfile
          tags: "${{ env.IMAGE_NAME }}:${{ matrix.version }}-test"
      - name: Pull Image
        run: docker pull "${{ env.IMAGE_NAME }}:${{ matrix.version }}-test"
      - 
        name: Extract Labels from Image
        id: extract-labels
        run: |
          LABELS=$(docker inspect "${{ env.IMAGE_NAME }}:${{ matrix.version }}-test" | jq -r '.[0].Config.Labels | to_entries | map("\(.key)=\(.value)") | join("\n")')
          echo "$LABELS"
          echo "$LABELS" >> labels.txt
          
          # Store in step output
          {
            echo "labels<<EOF"
            echo "$LABELS"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
      - 
        name: Push Labels as Manifest Annotations
        run: |
          # Create annotation arguments for buildx imagetools create
          LABEL_ARGS=$(echo "${{ steps.extract-labels.outputs.labels }}" | awk -F= '{print "--annotation "$1"="$2}')
          
          # Recreate the manifest list with annotations
          docker buildx imagetools create \
            $LABEL_ARGS \
            -t "${{ env.IMAGE_NAME }}:${{ matrix.version }}-test" \
            "${{ env.IMAGE_NAME }}:${{ matrix.version }}-test"
      -
        name: Grab Current Version
        id: current_version
        run: echo "CURRENT_NODE_VERSION=$(docker run ${{ env.IMAGE_NAME }}:${{ matrix.version }}-test node -v)" >> $GITHUB_ENV
      -
        name: Grab Minor Version
        id: minor_version
        run: echo "MINOR=$(node extract-semver.js ${{ env.CURRENT_NODE_VERSION }} minor)" >> $GITHUB_ENV
      -
        name: Grab Patch Version
        id: patch_version
        run: echo "PATCH=$(node extract-semver.js ${{ env.CURRENT_NODE_VERSION }} patch)" >> $GITHUB_ENV
      - 
        name: Check for specific node version
        id: check_specific_version
        run: |
          if [[ "${{ matrix.version }}" == *.* ]]; then
            echo "SPECIFIC_VERSION=true" >> $GITHUB_ENV
          else
            echo "SPECIFIC_VERSION=false" >> $GITHUB_ENV
          fi
      -
        name: Grab Major Version
        if: ${{ env.SPECIFIC_VERSION == 'true' }}
        id: major_version
        run: echo "MAJOR=$(node extract-semver.js ${{ env.CURRENT_NODE_VERSION }} major)" >> $GITHUB_ENV
      - 
        name: Retag, and push minor/patch images
        if: ${{ env.SPECIFIC_VERSION == 'false' }}
        run: |
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:${{ matrix.version }}.${{ env.MINOR }}-test ${{ env.IMAGE_NAME }}:${{ matrix.version }}-test
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ matrix.version }}.${{ env.MINOR }}-test
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:${{ matrix.version }}.${{ env.MINOR }}.${{ env.PATCH }}-test ${{ env.IMAGE_NAME }}:${{ matrix.version }}-test
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ matrix.version }}.${{ env.MINOR }}.${{ env.PATCH }}-test
      - 
        name: Retag, and push major/minor images
        if: ${{ env.SPECIFIC_VERSION == 'true' }}
        run: |
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:${{ env.MAJOR }}-test ${{ env.IMAGE_NAME }}:${{ matrix.version }}-test
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ env.MAJOR }}-test
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:${{ env.MAJOR }}.${{ env.MINOR }}-test ${{ env.IMAGE_NAME }}:${{ matrix.version }}-test
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ env.MAJOR }}.${{ env.MINOR }}-test

# I don't think we use the core images and we should consider removing this and the Dockerfile.core file.
      # -
      #   name: Build Core
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     platforms: linux/arm64,linux/amd64
      #     build-args: "NODE_VERSION=${{ matrix.version }}"
      #     pull: true
      #     push: true
      #     file: ./Dockerfile.core
      #     tags: | 
      #       "${{ env.IMAGE_NAME }}:${{ matrix.version }}-core-test"
      #       "${{ env.IMAGE_NAME }}:${{ matrix.version }}.${{ steps.minor_version.outputs.minor }}-core-test"
      #       "${{ env.IMAGE_NAME }}:${{ matrix.version }}.${{ steps.minor_version.outputs.minor }}.${{ steps.patch_version.outputs.patch }}-core-test"
