name: release
run-name: ${{ github.actor }} has triggered a build and push of the Terascope Base Image

on:
  release:
    types: [published]
  schedule:
    - cron: '30 5 * * 0'  # Sunday's at 0530
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/node-base

jobs:
  build_and_release_matrix:
    strategy:
      matrix:
        # NOTE: These versions must be kept in sync with the build.yml
        version: ["18", "18.19", "18.19.1", 
                  "20", "20.11", "20.11.1", 
                  "22", "22.2", "22.2.0"]

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64,linux/amd64
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          build-args: "NODE_VERSION=${{ matrix.version }}"
          pull: true
          push: true
          file: ./Dockerfile
          tags: "${{ env.IMAGE_NAME }}:${{ matrix.version }}"
      -
        name: Build Core
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          build-args: "NODE_VERSION=${{ matrix.version }}"
          pull: true
          push: true
          file: ./Dockerfile.core
          tags: "${{ env.IMAGE_NAME }}:${{ matrix.version }}-core"

      # Look into this more:
      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #     subject-digest: ${{ steps.build_and_release_matrix.outputs.digest }}
      #     push-to-registry: true
